/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bit_checker_6 (
    input [7:0] out,
    input [7:0] actual_out,
    output reg [7:0] io_led
  );
  
  
  
  integer i;
  
  always @* begin
    io_led = 8'h00;
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      if (out[(i)*1+0-:1] != actual_out[(i)*1+0-:1]) begin
        io_led[(i)*1+0-:1] = 1'h1;
      end
    end
  end
endmodule
