/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_adder_2 (
    input [7:0] a,
    input [7:0] b,
    input alufn0,
    output reg [7:0] sum,
    output reg z,
    output reg n,
    output reg v
  );
  
  
  
  reg [7:0] summ;
  
  always @* begin
    
    case (alufn0)
      1'h1: begin
        summ = a - b;
      end
      1'h0: begin
        summ = a + b;
      end
      default: begin
        summ = 8'h00;
      end
    endcase
    if (summ == 1'h0) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    if (summ[7+0-:1] == 1'h1) begin
      n = 1'h1;
    end else begin
      n = 1'h0;
    end
    v = a[7+0-:1] & (b[7+0-:1] ^ alufn0) & (~summ[7+0-:1]) | (~a[7+0-:1]) & (b[7+0-:1] ~^ alufn0) & (summ[7+0-:1]);
    sum = summ;
  end
endmodule
